# Generated by Django 6.1.1 on 2026-10-07 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Momento exacto en el que se creó el registro.', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Momento de la última modificación del registro.', verbose_name='Última actualización')),
                ('phone_prefix', models.CharField(default='+58', help_text='Prefijo telefónico internacional.', max_length=6, verbose_name='Código de país')),
                ('phone_number', models.CharField(blank=True, help_text='Número de teléfono o contacto del tutor.', max_length=20, verbose_name='Teléfono')),
                ('id_type', models.CharField(default='V', help_text='Nacionalidad o tipo de documento (V, E, J, P).', max_length=2, verbose_name='Tipo de documento')),
                ('id_number', models.CharField(blank=True, help_text='Número de identificación legal del tutor.', max_length=20, verbose_name='Número de cédula/documento')),
                ('bio', models.TextField(blank=True, help_text='Presentación o notas sobre el tutor.', verbose_name='Biografía')),
                ('user', models.OneToOneField(help_text='Cuenta de usuario vinculada al perfil.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
    ]
