# Generated by Django 6.1.1 on 2026-10-07 06:18

from django.db import migrations


def create_security_roles(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # Crear grupos de seguridad oficiales del sistema
    tutor_group, _ = Group.objects.get_or_create(name='Tutor')
    admin_group, _ = Group.objects.get_or_create(name='Administrador')

    # Asignar permisos estándar al grupo Tutor
    tutor_permissions = Permission.objects.filter(
        codename__in=[
            'view_userprofile',
            'change_userprofile',
        ]
    )
    tutor_group.permissions.set(tutor_permissions)

    # El grupo Administrador recibe todos los permisos de cuentas y auditoría
    admin_permissions = Permission.objects.filter(
        content_type__app_label__in=['accounts', 'core']
    )
    admin_group.permissions.set(admin_permissions)


def remove_security_roles(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Tutor', 'Administrador']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_security_roles, reverse_code=remove_security_roles),
    ]

