# Generated by Django 6.1.1 on 2026-10-07 06:19

from django.contrib.auth.hashers import make_password
from django.db import migrations

DEV_PASSWORD = '123456789'

DEV_USERS = [
    {
        'username': 'admin',
        'email': 'admin@petly.com',
        'first_name': 'Admin',
        'last_name': 'Petly',
        'group': 'Administrador',
        'is_staff': True,
        'is_superuser': True,
        'profile': {
            'phone_prefix': '+58',
            'phone_number': '4120000000',
            'id_type': 'V',
            'id_number': '00000001',
            'bio': 'Administrador del sistema Petly.',
        },
    },
    {
        'username': 'edwyn',
        'email': 'edwyn@petly.com',
        'first_name': 'Edwyn',
        'last_name': 'Guzmán',
        'group': 'Tutor',
        'is_staff': False,
        'is_superuser': False,
        'profile': {
            'phone_prefix': '+58',
            'phone_number': '4241234567',
            'id_type': 'V',
            'id_number': '27456789',
            'bio': 'Backend Developer en Petly.',
        },
    },
    {
        'username': 'stefany',
        'email': 'stefany@petly.com',
        'first_name': 'Stefany',
        'last_name': 'Martínez',
        'group': 'Tutor',
        'is_staff': False,
        'is_superuser': False,
        'profile': {
            'phone_prefix': '+58',
            'phone_number': '4142345678',
            'id_type': 'V',
            'id_number': '28123456',
            'bio': 'Frontend Developer en Petly.',
        },
    },
    {
        'username': 'bryan',
        'email': 'bryan@petly.com',
        'first_name': 'Bryan',
        'last_name': 'Silva',
        'group': 'Tutor',
        'is_staff': False,
        'is_superuser': False,
        'profile': {
            'phone_prefix': '+58',
            'phone_number': '4123456789',
            'id_type': 'V',
            'id_number': '26987654',
            'bio': 'Database Administrator en Petly.',
        },
    },
    {
        'username': 'oriana',
        'email': 'oriana@petly.com',
        'first_name': 'Oriana',
        'last_name': 'Arellano',
        'group': 'Tutor',
        'is_staff': False,
        'is_superuser': False,
        'profile': {
            'phone_prefix': '+58',
            'phone_number': '4164567890',
            'id_type': 'V',
            'id_number': '27345678',
            'bio': 'UX/UI Developer en Petly.',
        },
    },
    {
        'username': 'maria',
        'email': 'maria@petly.com',
        'first_name': 'María Paula',
        'last_name': 'Herrero',
        'group': 'Tutor',
        'is_staff': False,
        'is_superuser': False,
        'profile': {
            'phone_prefix': '+58',
            'phone_number': '4245678901',
            'id_type': 'V',
            'id_number': '26123987',
            'bio': 'Product Owner en Petly.',
        },
    },
    {
        'username': 'sofia',
        'email': 'sofia@petly.com',
        'first_name': 'Sofía',
        'last_name': 'Marcano',
        'group': 'Tutor',
        'is_staff': False,
        'is_superuser': False,
        'profile': {
            'phone_prefix': '+58',
            'phone_number': '4146789012',
            'id_type': 'V',
            'id_number': '27890123',
            'bio': 'Product Owner en Petly.',
        },
    },
    {
        'username': 'tutor',
        'email': 'tutor@petly.com',
        'first_name': 'Tutor',
        'last_name': 'Petly',
        'group': 'Tutor',
        'is_staff': False,
        'is_superuser': False,
        'profile': {
            'phone_prefix': '+58',
            'phone_number': '4240001122',
            'id_type': 'V',
            'id_number': '25555444',
            'bio': 'Tutor responsable de prueba en Petly.',
        },
    },
]


def create_dev_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')
    UserProfile = apps.get_model('accounts', 'UserProfile')

    admin_group, _ = Group.objects.get_or_create(name='Administrador')
    tutor_group, _ = Group.objects.get_or_create(name='Tutor')

    groups_map = {
        'Administrador': admin_group,
        'Tutor': tutor_group,
    }

    for user_data in DEV_USERS:
        user, created = User.objects.get_or_create(
            username=user_data['username'],
            defaults={
                'email': user_data['email'],
                'password': make_password(DEV_PASSWORD),
                'first_name': user_data['first_name'],
                'last_name': user_data['last_name'],
                'is_staff': user_data['is_staff'],
                'is_superuser': user_data['is_superuser'],
            },
        )
        if not created:
            user.password = make_password(DEV_PASSWORD)
            user.email = user_data['email']
            user.first_name = user_data['first_name']
            user.last_name = user_data['last_name']
            user.is_staff = user_data['is_staff']
            user.is_superuser = user_data['is_superuser']
            user.save()

        target_group = groups_map.get(user_data['group'])
        if target_group:
            user.groups.add(target_group)

        profile_data = user_data['profile']
        UserProfile.objects.update_or_create(
            user=user,
            defaults={
                'phone_prefix': profile_data['phone_prefix'],
                'phone_number': profile_data['phone_number'],
                'id_type': profile_data['id_type'],
                'id_number': profile_data['id_number'],
                'bio': profile_data['bio'],
            },
        )


def remove_dev_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    usernames = [u['username'] for u in DEV_USERS]
    User.objects.filter(username__in=usernames).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_security_roles'),
    ]

    operations = [
        migrations.RunPython(create_dev_users, reverse_code=remove_dev_users),
    ]

