# Generated by Django 6.1.1 on 2026-10-07 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_create_dev_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('id_number', ''), _negated=True), fields=('id_type', 'id_number'), name='unique_tutor_identity_document'),
        ),
    ]
