# Generated by Django 6.1.1 on 2026-10-03 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Momento exacto en el que se creó el registro.', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Momento de la última modificación del registro.', verbose_name='Última actualización')),
                ('action', models.CharField(help_text='Descripción de la acción o evento auditado.', max_length=150, verbose_name='Acción')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde la cual se ejecutó la acción.', null=True, verbose_name='Dirección IP')),
                ('details', models.TextField(blank=True, help_text='Información complementaria sobre la acción ejecutada.', verbose_name='Detalles adicionales')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario asociado al evento de auditoría.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de auditoría',
                'verbose_name_plural': 'Logs de auditoría',
                'ordering': ['-created_at'],
            },
        ),
    ]
